### ISSUE TITLE
Instanziierung aller FHIR-Ressourcen als Klasse

### ISSUE THREAD

**Issue by vnf1** [i4mi/midata.js#5]
Zur Zeit werden nur die "registrierten" Ressourcen (z.B. BodyWeight) als Klassen instanziiert, die anderen werden als JSON-Objekt instanziiert.

Alle Ressourcen sollten als Klasse instanziiert werden (z.B. MedicationStatement, Observation oder zumindest Resource). Dafür muss die "Registrierung" ausgebaut werden: zusätzlich zum Code muss auch den Ressourcetyp in der Mappingtabelle aufgenommen und berücksichtigt werden.

**Comment by wyssa14** [comment]
Ich denke, wir brauchen etwas in dieser Art:

https://stackoverflow.com/questions/5873624/parse-json-string-into-a-particular-object-prototype-in-javascript
